### ISSUE TITLE
Mem. corruption causing inconsistent threat behaviour

### ISSUE THREAD

**Issue by duivos** [Ay-can/booky#3]
I've noticed an issue related to memory integrity and its impact on thread synchronization. It seems that memory corruption is leading to irregular behavior during the execution of threads, resulting in inconsistent outcomes.

- I've identified instances where memory integrity is compromised, leading to unexpected states in threads and disrupting their normal flow.
- Interactions with the bookshelf are displaying inconsistencies, which could be attributed to the memory corruption affecting data synchronization.
- The root cause of the memory corruption remains unidentified and requires further investigation to resolve.

**Comment by Ay-can** [comment]
skill issue

**Comment by Ay-can** [comment]
This is fixed now in **"Improved Key Event Handling, Dependency Updates, and FocusEvent Fix"** #4
